'@saphe/react-form':
  - packages/react-form/*
  - packages/react-form/**/*
'@saphe/react-form-fields-bootstrap':
  - packages/react-form-fields-bootstrap/*
  - packages/react-form-fields-bootstrap/**/*
'@saphe/react-table':
  - packages/react-table/*
  - packages/react-table/**/*
'@saphe/react-use':
  - packages/react-use/*
  - packages/react-use/**/*
