name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  run:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@master

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        id: pnpm-install
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Upload @saphe/react-use coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./packages/react-use/.coverage/coverage-final.json
          flags: '@saphe/react-use'

      - name: Upload @saphe/react-form coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./packages/react-form/.coverage/coverage-final.json
          flags: '@saphe/react-form'

      - name: Upload @saphe/react-form-fields-bootstrap coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./packages/react-form-fields-bootstrap/.coverage/coverage-final.json
          flags: '@saphe/react-form-fields-bootstrap'

      - name: Upload @saphe/react-table coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./packages/react-table/.coverage/coverage-final.json
          flags: '@saphe/react-table'
