name: Release

on:
  push:
    branches:
      - main

jobs:
  run:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Upload @saphe/react-use coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./packages/react-use/.coverage/coverage-final.json
          flags: '@saphe/react-use'

      - name: Upload @saphe/react-form coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./packages/react-form/.coverage/coverage-final.json
          flags: '@saphe/react-form'

      - name: Upload @saphe/react-form-fields-bootstrap coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./packages/react-form-fields-bootstrap/.coverage/coverage-final.json
          flags: '@saphe/react-form-fields-bootstrap'

      - name: Upload @saphe/react-table coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./packages/react-table/.coverage/coverage-final.json
          flags: '@saphe/react-table'

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
